import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";


const quickSand = Quicksand({
  variable: "--font-family",
  subsets: ["latin"],
  weight: ['300','400','500','700'],
  display:'swap'
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Expense App",
  description: "Generated by Watuulo Richard",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quickSand.variable} antialiased bg-slate-800/90`}
      >
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
